# для локального запуска
#spring:
#  application:
#    name: getaway-server
#  config:
#    import: optional:configserver:http://localhost:8071
#jwt:
#  public-key: ${JWT_PUBLIC_KEY}

spring:
  application:
    name: getaway-server
  config:
    import: optional:configserver:http://config-server:8071
jwt:
  public-key: ${JWT_PUBLIC_KEY}