global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - order-service:8180
          - shop-service:8181
          - payment-service:8182
          - history-service:8184
          - getaway-server:8072
          - notification-service:8183