# для локального запуска
#spring:
#  application:
#    name: eureka-server
#  config:
#    import: optional:configserver:http://localhost:8071

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://config-server:8071